<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="amit" tests="2" failures="1" timestamp="30 Jan 2016 04:55:40 GMT" time="1.047" errors="0">
  <testcase name="testAddTwoNumbers" time="0.014" classname="TestCalc"/>
  <testcase name="testAddTwoStringNumbers" time="1.01" classname="TestCalc">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testAddTwoStringNumbers() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testAddTwoStringNumbers() didn't finish within the time-out 1000
	at java.lang.Thread.currentThread(Native Method)
	at java.util.concurrent.locks.ReentrantLock$Sync.isHeldExclusively(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signalAll(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.tryTerminate(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testAddTwoStringNumbers -->
</testsuite>
